### PR TITLE
ENHANCEMENT: Update all task elements to standardized syntax 

### PR DESCRIPTION
**Pull request by bcurran3**
**What this PR does / why we need it**:

Updates all task elements to standardized syntax. This is a beautification enhancement and nothing more.

**name: xxxxxxxxxx** inside (app) tasks now has uniform syntax as **Create < app > Docker Container** and **Create < app > Directories** with consistent spelling, capitalization, proper app name, etc. where before there was multiple styles of syntax.

**Which issue (if any) this PR fixes**:

Fixes #

**Any other useful info**:

Output of the playbook is now more consistent and professional looking

### CODE REVIEW

**Comment by bcurran3** [comment]
image

**Comment by davestephens** [comment]
I like changes like this - but it's a waste of time unless it can be enforced with build conditions (as we do with markdown linting for example) otherwise it drifts over time. 

Any thoughts how we could do that?

Also, please squash down to one commit.

**Comment by bcurran3** [comment]
Sorry but I now nothing of GH CI. 

I also don't know how to "squash down to one commit" - I just edited files and saved them to the same clone/patch. I don't know any other way.

As for how to get possibly get this type of thing "under control" for the future, two things:
1. I'm of the belief that most people copy, paste, then edit. If my theory is correct, after this PR is pulled, the source used to copy, paste, then edit will be standardized and we can hope for more standardized results in new apps added to AN.
2. I've been considering submitting a commented templet role  that contributors can use as a base to copy, paste, then edit. I'm very happy to do this, and with a lot of comments, but I want to know you're likely to pull it in first.

**Comment by bcurran3** [comment]
> I like changes like this - but it's a waste of time unless it can be enforced with build conditions (as we do with markdown linting for example) otherwise it drifts over time.

p.s. Um, the submissions get reviewed by a human who catches other minutiae. :-)

**Comment by davestephens** [comment]
> Sorry but I now nothing of GH CI.

> I also don't know how to "squash down to one commit"

A Google search will help you for both of these.

>  p.s. Um, the submissions get reviewed by a human who catches other minutiae. :-)

Yes, but I don't/won't catch everything. CI will mean I don't have to.

**Comment by bcurran3** [comment]
This is complicated for me as I don't use GH Desktop and GH won't allow me to pull down only this [patch](https://github.com/bcurran3/ansible-nas/tree/patch-61.git) for me to play with temporarily and push back. Sorry but I'm only an amateur "developer."

The changes are really simple and easy to view. I'm guessing the [review display](https://github.com/davestephens/ansible-nas/pull/583/files) would look the 99% the same if it's squashed or not. Would you be a dear and review the changes and then choose the squash and merge choice if everything is kosher please?

REF: https://stackoverflow.com/questions/35948131/github-squash-commits-from-web-interface-on-pull-request-after-review-comments

**Pull request closed without merging**
