### PR TITLE
Add minidlna

### PR DESCRIPTION
**Pull request by burrowsa**

### CODE REVIEW

**Comment by davestephens** [comment]
Awesome, thank you for the contribution!

**Comment by koenvervloesem** [comment]
This gives me the following error:

    fatal: [localhost]: FAILED! => {"msg": "The conditional check 'minidlna_enabled' failed. The error was: error while evaluating conditional (minidlna_enabled): 'minidlna_enabled' is undefined\n\nThe error appears to have been in '/home/koan/ansible-nas/tasks/minidlna.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: minidlna Docker Container\n  ^ here\n"}

**Comment by koenvervloesem** [comment]
Oh sorry, I forgot I had to add `minidlna_enabled` to `group_vars/all.yml` :-)

**Comment by davestephens** [comment]
Are you sure you've merged the latest changes in all.yml.dist into your own
all.yml?

That particular piece of config (`minidlna_enabled`) is there in the dist
config so I'm wondering if you've missed it...

**Comment by koenvervloesem** [comment]
Yes, sorry, I missed it. Just installed ansible_nas this weekend, so I'm still finding my way through the system... Just ignore my remark :-) This is a really awesome system, keep up the good work!

**Pull request merged**
