### PR TITLE
Add bitwarden service

### PR DESCRIPTION
**Pull request by jesse-troy**
Bitwarden is a password management tool, similar to LastPass.

This version of bitwarden is in a single docker container as opposed to the official version which creates something like 6 containers. It also includes a backup tool that will automatically create a backup at 5 a.m. every day. This tool can be configured as well.

### CODE REVIEW

**Comment by davestephens** [comment]
Ok...so just pulled this and tried to run it up on the Vagrant test Ansible-NAS and it doesn't appear to be working. Any ideas? How do I test it so that I know it's good to merge? :)

**Comment by scotws** [comment]
@davestephens Are you having the same issue as #74 ? That's some weird version mismatch, but I don't understand Vagrant enough to do much more than point out it isn't working for me either.

**Comment by davestephens** [comment]
@scotws Nah Vagrant is working fine, I'm not *that* stupid ;-)

**Comment by davestephens** [comment]
OK so I got my brain into gear and did some more testing on this - it works fine (obvs) but not when spun up within Vagrant. Seems to be the extra hop across into Vagrant screws it up - but whatever - if you `vagrant ssh` and `curl` the web port, everything is listening as expected. 

I've pushed some tweaks which *should* fix the WebSocket thing too, so gonna test that later this evening...

I also fixed the mega merge smash that was my own doing, and have merged your work. Thanks for the contribution! :+1:

**Comment by jesse-troy** [comment]
Okay great! In my testing, it seemed ot work best without websockets (I thoght I had it commented out, my bad). Websockets really only allows "instant" synchronization with web extensions. I was going to work on it some this week, but it looks like you found the fix, to use the traefik protocol!

**Pull request merged**
