### PR TITLE
Add some software

### PR DESCRIPTION
**Pull request by tcharewicz**
+ bugfix at roles nas.yml file
+ add plex
+ add plexpy
+ add deluge
+ add TVheadend
+ add Unifi Controller

### CODE REVIEW

**Comment by davestephens** [comment]
Thanks for your contribution, this is awesome!

The PR is pretty much there, but a few small things need a bit of love. I've added comments to the commits, but also:

- You've set all of the containers to be disabled by default - previously you'd get a base NAS system with some functionality. It needs to be noted in the readme that the user is expected to enable the stuff they want.

- What was the bugfix to nas.yml?

- There are a number of files that are showing as having committed changes that aren't actually changed (I think this might be down to wonky local git settings):
    - inventory
    - templates/docker/daemon.json
    - tasks/general.yml

**Comment by DawnTreader** [comment]
Please forgive me ahead of time. I have no idea how git, pulls, commits and all this stuff here works. I have heard about github and stuff a lot but have never bothered to get into it as I don't do as much code work as I used to.

On to why I am here. I am tired of worrying about my FreeNAS box. It has been stable for a long while now but just recently started throwing a new error I haven't seen and I am unsure if it is a real problem or not.

I use the FreeNAS for 2 things, Media, specifically Plex and MineOS. I have a few servers running that my 2 boys and I use.

Is MineOS available to this setup?

**Comment by davestephens** [comment]
@DawnTreader might be easier to open a new issue if you have more questions, but in short - yes. MineOS is available as a Docker image which you can pull and run on ansible-nas.

**Comment by davestephens** [comment]
Closing as not heard anything back.

**Comment by tcharewicz** [comment]
Sorry for a long lack of answer. I will prepare a new PR for my changes with your comments.

**Comment by davestephens** [comment]
No probs. If you're planning on adding extra functionality, please can you
add one new thing per PR?

Thanks!

**Pull request closed without merging**
