### PR TITLE
add gotify application

### PR DESCRIPTION
**Pull request by random-dwi**
**What this PR does / why we need it**:
Gotify is an application that can be used to send push notifications.
There are also apps for mobile, so you can send push notifications to your phone.

This can for example be configured in Duplicati to inform about a backup that was made or in Pyload for all kinds of events.

### CODE REVIEW

**Comment by davestephens** [comment]
This is awesome, it has been on my list for ages to add. 

Nearly ready to merge, but I think we need to mount the container data directory?

**Comment by random-dwi** [comment]
Oh of course. I forgot. Otherwise mesages might get lost when the container is restarted.
I will fix that...

**Comment by bcurran3** [comment]
https://github.com/davestephens/ansible-nas/pull/264 was ready May 2020 but never merged. :(

**Comment by random-dwi** [comment]
@bcurran3 sorry, did not check the open PR's before making my own.
Since, my PR is based on the new role "structure" I tried to cover everything from your PR in mine.
I hope your are fine with that.

**Comment by bcurran3** [comment]
@random-dwi - You're all good. The comment wasn't directed at you. Just pointing it out, maybe a humble grumble(tm).

I have many PR's open from the first half of 2020 that have never been commented on or even acknowledged. I just find it weird that PR's are being merged LIFO instead of looked at FIFO.

**Comment by davestephens** [comment]
@bcurran3 Off topic for this PR, but I need to convert all of your PRs to
the new role structure and then merge, they will get done! I didn't really
want to much a bunch of PRs that will lump me with a bunch of tech debt to
deal with straight after.

**Comment by bcurran3** [comment]
@davestephens - I'm way behind in AN merges locally since I've got so much added... my PRs and more. I've shied away from upgrading because of the work. Would be happy to upgrade myself and then work on converting my task PRs to role based. Just need to know they're welcome before I commit (pun), errrr, pull.

**Comment by davestephens** [comment]
> @davestephens - I'm way behind in AN merges locally since I've got so much added... my PRs and more. I've shied away from upgrading because of the work. Would be happy to upgrade myself and then work on converting my task PRs to role based. Just need to know they're welcome before I commit (pun), errrr, pull.

For sure, just need to get them up to date - roles, Traefik 2 etc.

**Pull request merged**
