### PR TITLE
gotify.md addition for Gotify

### PR DESCRIPTION
**Pull request by bcurran3**

### CODE REVIEW

**Comment by davestephens** [comment]
I'm a little confused why you're spreading one feature across multiple pull requests? 🤔 This and the other change related to gotify should be in the same PR...

**Comment by bcurran3** [comment]
I'm pretty much GH dumb. I can push and pull. Branching, merging, rebasing, etc. are all pretty foreign to me and every time I try I screw something up.

I cloned ansible-nas and then added the PyTivo additions to my master branch. I didn't know then that (I think) I should have created a new branch. So right now if I try to add anything new and do a PR it pulls the older PyTivo stuff with it on top of the newer stuff. Thus I'm waiting for PyTivo to get merged so I can basically deleted my ansible-nas cloned repo and try again. I'm learning.

For the moment editing the files directly on your repo by pasting in my additions seems to be the easiest way for me to not screw things up. Sorry for any extra work on your part.

**Comment by davestephens** [comment]
You're causing me a lot of admin in the process :-) The reason why I (and every other open source maintainer) request a single feature per pull request is because it's a nightmare to see how your entire change set will affect the repo. I also have no way of actually testing this, unless I merge 6(?) pull requests into one, making the repo history look a mess. 

I really appreciate the contribution, but you need to learn git basics and how to clone, branch, and raise pull requests.

**Comment by bcurran3** [comment]
So what's the status here?

Planning to process? On hold? Requesting re-submitting in a more maintainer desired state?

**Comment by davestephens** [comment]
Yeah, it needs to be in one PR I'm afraid.

**Comment by bcurran3** [comment]
Can't say I'm happy (and have arguments against) but will comply.

This wouldn't be an issue of https://github.com/davestephens/ansible-nas/pull/181 was merged.

I've got 3+ additions on hold.

**Comment by davestephens** [comment]
I'm sorry, but there is no argument in favour of a changeset having a pull
request (and associated branch!) per file you change.

Furthermore, a pull request gives us one place to discuss and review the
change before a single branch is merged. Say we want to discuss something
about Gotify in general, which of the pull requests does the discussion go
in?

Have a read of this.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by bcurran3** [comment]
> I'm sorry, but there is no argument in favour of a changeset having a pull request (and associated branch!) per file you change. 

I can argue for or against anything, the world is not as black and white as you surmise...  and there are definitely arguments for this, in fact, I've already stated them.

> Furthermore, a pull request gives us one place to discuss and review the change before a single branch is merged. Say we want to discuss something about Gotify in general, which of the pull requests does the discussion go in? 

Of course. That's all obvious. I never said I wanted to do the PRs that way and I never said it should be that way, I stated WHY I did it that way when asked. My preference would have been one PR as well. You completely missed the root cause.

> Have a read of this. https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

Just did. It was 100% devoid of anything related to my problem. I know how to create a PR, you've seen that. What I need to understand more is about branches. You completely missed the root cause. Reading comprehension error.

**Comment by davestephens** [comment]
Whether you consider a feature should have multiple pull requests or not, that's not how I'd like features raised for Ansible-NAS. It causes a lot of admin, it pollutes the git history, and it makes it difficult to reason about an entire change set in one place.

I haven't bent the rules before, and I don't intend to now, especially when the reason is that you don't know how to create branches in git. The [contribution doc](https://github.com/davestephens/ansible-nas/blob/master/CONTRIBUTING.md) states very clearly "one feature per pull request". Not "multiple features per pull request" or "multiple pull requests per feature. It has been like this since the project started, and in the contribution docs in black and white for a year. Furthermore, the doc is linked for you every time your raise a PR. If you choose to ignore that, then don't be surprised when your PRs get rejected for the reasons previously stated to you.

If you then think "well I don't know how to create a branch" or "I don't know what a pull request is", then please do some research. The answers to your questions are easily found on the internet - the [first Google result](https://guides.github.com/introduction/flow/) for "github git branching" is something you should probably read and would save us both a lot of time. 

You must understand that it's not my job to teach you everything you don't know because you've decided to use open source software you found on the internet, run by people in their *free time* because *they enjoy it*. 

I will reiterate the offer of help through the [Gitter chat room](https://gitter.im/Ansible-NAS/Chat) - which you previously declined because you decided the room was "dead" (that really is not the case) - but I would request that you read the newly formed [Code of Conduct](https://github.com/davestephens/ansible-nas/blob/master/CODE_OF_CONDUCT.md) first. This is *not* a place to hurl "reading comprehension" every time you read something you might not agree with.

**Comment by bcurran3** [comment]
Wow. This conversation should really have ended after I said **I "will comply**."

-----

> This is not a place to hurl "reading comprehension" every time you read something you might not agree with.

Never happened. Not once. I haven't even disagreed with anything!

I'm saddened that you misread or misinterpret most of what I say. There is a major disconnect between my giving reasons for past actions and your evident interpretation that those actions are to be continued and are some sort of argument for change. That last statement proves it even further. I'll take the blame on on evidently not communicating effectively. My bad. I guess I didn't make it clear that there was no real disagreement.

To end on a positive note, all of your reasoning and guidance is 100% solid and nothing has been disagreed with by me.

**Pull request closed without merging**
