### PR TITLE
Pytivo addition

### PR DESCRIPTION
**Pull request by bcurran3**

### CODE REVIEW

**Comment by animeai** [comment]
This is really old software... Does it still actually work? Personally, I'm somewhat uncomfortable with unmaintained software and docker images... 

Don't forget to run "ansible-lint nas.yml" on your branch before submitting the PR - you've got trailing whitespace issues.

**Comment by bcurran3** [comment]
Thanks for the wonderful work on ansible-nas, much appreciated. My additions don't seem to be of interest to the project so I'll just use my fork and not bother you.

**Comment by animeai** [comment]
@bcurran3 You can't even answer a question about whether the software still works? Enjoy your rage quit I guess.

**Comment by bcurran3** [comment]
I will enjoy my "rage quit."

I've been trying to be active in this community for months. Except for the Samba additions I've received nothing but pushback on EVERYTHING. There's obviously no value to my suggestions. I've completed 4 of my own enhancement requests and 2 other people's. I want to contribute, but I'm beating my head against the wall going nowhere.

"Does it still actually work?" Is a completely ignorant question as #1 see https://github.com/davestephens/ansible-nas/issues/149 #2 why the hell would I want to submit it to the rest of the community if it doesn't work? I'm happily using it. I'm probably only 1/640 that will use it currently. I'm probably one of ten who might ever use it. 

You want to talk CODE_OF_CONDUCT.md? How about a single modicum of respect for volunteers such as me trying to contribute to the project? I'm not seeing it. Some serious management of the project to consider: #1 encourage people who want to contribute #2 respect volunteers time and effort #3 when they say their going to take on an issue, assign it to them and mark it in progress. This creates a feeling of ownership and responsibility which turns into dedication. #4 READ what they say and attempt to understand it instead of skimming it, misunderstanding it, and giving knee jerk defensive responses that aren't necessary. #5 Try to promote positivism instead of negativity.

So yes. I'm the asshole who is "rage quitting" because he feels completely unappreciated. 

I got what I needed out of ansible-nas. I've modified it to suit my needs. I'm good with what I've got and I have the capability to continue adding on to any future wants and needs. ansible-nas is cookie cutter cut and paste, easy to understand in an hour or two. I wanted to contribute back and make it better. Thank you, really, for giving me an excellent starting base. You've done a good job and I see it getting better.

**Comment by animeai** [comment]
I think "does software abandoned by the dev in 2013 with no updates for over 2 years still work" is a very good question to ask. You yourself admit that pretty much nobody else will want to use it too. I've tried to help you multiple times and either been ignored or rebuffed. You seem to expect everybody to have an idetic memory for anything you've ever posted and have rejected or ignored all the help and advice provided. You are arrogant and entitled and this project will be better without you. Enjoy your fork, I hope it does everything you need it to.

**Comment by bcurran3** [comment]
> I think "does software abandoned by the dev in 2013 with no updates for over 2 years still work" is a very good question to ask. You yourself admit that pretty much nobody else will want to use it too. I've tried to help you multiple times and either been ignored or rebuffed. You seem to expect everybody to have an idetic memory for anything you've ever posted and have rejected or ignored all the help and advice provided. You are arrogant and entitled and this project will be better without you. Enjoy your fork, I hope it does everything you need it to.

1> I call BULLSHIT. You offered help. When I tried to take you up on your offer, you dismissed it. BTW: All I needed to know was click on the master branch button on GH and enter in a name for a new branch before entering a commit. It was that simple of a hurdle to overcome.

2> "this project will be better without you" Now who's the asshole? I'm passionate in what I do and I'm a guy who, by nature, likes to help others and fulfill their requests. It's ignorant statements like the one you just said that pushes people away. You have no clue of what I might have done. You're a completely ignorant dumb ass. Refer back to my management suggestions. You've obviously are not management material and should be labeled "does not play well with others." If you had the slightest potential for decency you would have simply said "Sorry, let's reboot and start this again and have a productive relationship instead of adversarial one." Nope, guess it's an alien concept to you. For the record I've not rejected, ignored, or rebuffed any advice. You too must have a reading compression issue as there is no way you can find proof of what you say, only the contrary.

**Comment by bcurran3** [comment]
@davestephens - sorry to be toxic. Not being disrespectful to the project, just doing an "exit interview" and trying to provide constructive criticism before I was attacked.

**Comment by davestephens** [comment]
A few words, if I may.

- Name-calling, personal attacks and bad language are not acceptable, and will not be tolerated on this project, end of. We're on GitHub here folks, a public platform that the world has access to. This is not Fidonet in 1996. 

- There are [contribution guidelines](https://github.com/davestephens/ansible-nas/blob/master/CONTRIBUTING.md) and a [Code of Conduct](https://github.com/davestephens/ansible-nas/blob/master/CODE_OF_CONDUCT.md). They are expected to be followed, by everyone. 

- Ansible-NAS (and other open source projects) are not the place to be spoon-fed every piece of knowledge you don't yet have. Doing your own research is very much expected of contributors. People will help get you up to speed, but they're not going to do your work for you. This is not the first time I've highlighted this to you @bcurran3 ([first time in October 2019](https://github.com/davestephens/ansible-nas/issues/158#issuecomment-544670177)) so I'm slightly disappointed we seem to be having this same conversation again three months later.

- If someone offers help to get you from a to b, accept it. Don't ignore it then complain that you haven't been told the right things or in the right way you wanted to hear.

On this note, you've been offered assistance by me personally [multiple](https://github.com/davestephens/ansible-nas/pull/197#issuecomment-571801476) [times](https://github.com/davestephens/ansible-nas/pull/197#issuecomment-572752520), and @animeai [probably](https://github.com/davestephens/ansible-nas/pull/197#issuecomment-571796606) [equally](https://github.com/davestephens/ansible-nas/pull/197#issuecomment-572743213) as many, if not more times. I don't know why you haven't taken up these offers.

- Patience when dealing with open source projects is very much something you need. [As I said to you yesterday](https://github.com/davestephens/ansible-nas/pull/195#issuecomment-572670384), I run Ansible-NAS in my free time, because I enjoy it. I don't get paid (running Ansible-NAS has made me < £100 over the years), it is not a business, and I have a real life away from the computer. So if it takes time to get to your PRs or issues, or they get blocked behind other PRs, that's just how it is and you need to suck it up.

[As I've said previously](https://github.com/davestephens/ansible-nas/pull/195#issuecomment-571303425), I'm truly grateful for yours (and everyone else's) contributions but you need to put the effort in getting up to speed with the tooling required to contribute. Me rejecting your PRs because you've not done this is not "pushback", it's calling "running a project with standards". If I allowed everything to be merged that was raised in a PR with absolutely no standards or quality being upheld, then the project wouldn't be of the same quality that it is now. The project doesn't owe you anything, and it's not a piece of software you pay for, so effort absolutely *is* required on your part too.

I'd still be happy for you to contribute to the project, but you need to:
- listen to advice you've been given multiple times over the last few months
- be nice to people
- put effort into learning the tooling
- realise that "your way" is not necessarily "the right way", and that people here that will disagree with you from time to time. 

If this doesn't sit well with you, then I would suggest that Ansible-NAS is maybe not the project for you. I wish you well in your future endeavours should you choose to move on.

**Pull request closed without merging**
