### PR TITLE
Support iSpy AgentDVR

### PR DESCRIPTION
**Pull request by darshitpp**
**What this PR does / why we need it**:
For my home server, one often requires a capability to record their CCTV cameras. I found the iSpy AgentDVR to be easy to setup and use, and used the repo to deploy it for my needs. Raising a PR for the same!

More info on the software:
`https://www.ispyconnect.com/`

### CODE REVIEW

**Comment by davestephens** [comment]
Please can we remove all the stuff not related to ispydvr?

**Review by davestephens — CHANGES_REQUESTED** [review]
Please can we remove all the stuff unrelated to ispy agentdvr?

**Comment by darshitpp** [comment]
@davestephens I have addressed the review comments. Please let me know if any more changes are needed.

**Review by davestephens — APPROVED** [review]

**Comment by davestephens** [comment]
Awesome, thank you! Apologies for taking so long to get to your PR...

**Pull request merged**
