### PR TITLE
Add Minecraft Server image

### LINKED ISSUE #531: Add Minecraft Server
**Application you'd like to add:** Minecraft Server

**Link to Docker image:** https://hub.docker.com/r/itzg/minecraft-server

**Why you'd like this application added:** I'd like to run Minecraft Server on my server running Ansible NAS.

### PR DESCRIPTION
**Pull request by fetherolfjd**
**What this PR does / why we need it**:

Add the `itzg/minecraft-server` image as the `Minecraft Server` application to be run within Ansible NAS. This is needed because some people (me) would like to easily run a vanilla Minecraft server instance on the server running Ansible NAS.

**Which issue (if any) this PR fixes**:

Fixes #531 

**Any other useful info**:

Thanks for Ansible NAS!

### CODE REVIEW

**Comment by davestephens** [comment]
Nice, a good start!

Looking forward to seeing this tidied up with docs etc.

Does it require external access?

**Comment by fetherolfjd** [comment]
Thanks, I'm hoping to be able to set aside some more time to work on this tonight. Regarding external access: no, there's no UI or anything to configure access through Traefik.

**Comment by fetherolfjd** [comment]
@davestephens I think this is all ready to go. Let me know any thoughts you've got; thanks!

**Comment by fetherolfjd** [comment]
@davestephens Looks like the linting failed with a file for Ubooquity; do you want me to fix that in this PR?

**Comment by davestephens** [comment]
I think I've fixed it on master, if you merge from master to your branch we should be good to go :+1:

**Comment by fetherolfjd** [comment]
Merge from `master` complete.

**Comment by davestephens** [comment]
Awesome, thanks! :+1:

**Pull request merged**
