### PR TITLE
Ansible posix nfs

### PR DESCRIPTION
**Pull request by fabricesemti80**
**What this PR does / why we need it**:

**Which issue (if any) this PR fixes**:

Fixes #

**Any other useful info**:

### CODE REVIEW

**Comment by fabricesemti80** [comment]
sorry - meant to my fork

**Comment by davestephens** [comment]
Looks like you have some nice stuff in there though if you're keen to raise
a PR :-)

**Comment by fabricesemti80** [comment]
Haha... yeag I can, although not too proud on my fumbling with traefik oauth :)

**Comment by fabricesemti80** [comment]
I cleaned up my version slightly. If you want you can merge it from here -> I explained what I changed, but feel free to compare it to your work. 

https://github.com/fabricesemti80/ansible-nas-docker/pull/6#issue-1408310875

Did not added the ansible.posix yet, but I consider, as I use nfs shares and too lazy to edit /etc/fstab if I have to rebuild :D

Otherwise - thanks for this great piece of work, appreciate it. (Had docker-compose / k8s in the past, but this is just more confi than both!)

Ta

**Pull request closed without merging**
