### PR TITLE
FIX: FreshRSS - add REQUIRED db to task (part 2)

### PR DESCRIPTION
**Pull request by bcurran3**
- added new variables for Postgres DB addition

**What this PR does / why we need it**:

**Which issue (if any) this PR fixes**:

Fixes #

**Any other useful info**:

### CODE REVIEW

**Review by davestephens — CHANGES_REQUESTED** [review]
Please can you add this to #565

**Comment by bcurran3** [comment]
Glad to if I can figure out HOW to.

**Comment by bcurran3** [comment]
I figured it out - YAY!

**Comment by davestephens** [comment]
Roll back this commit, change to the other branch attached to the other PR,
commit again - should be all!

**Comment by bcurran3** [comment]
I added the contents (plus some) of this PR to https://github.com/davestephens/ansible-nas/pull/565. So I'm confused why you want me to do anything with this closed PR?  

image

**Pull request closed without merging**
