### PR TITLE
Fix issue #35 - Traefik requests production cert by default

### PR DESCRIPTION
**Pull request by C-J1**
First cut at fixing issue #35. I'm not able to test this properly at home at the moment. I should be able to do some proper testing on the weekend, but I think this is ok. If someone can test sooner, that'd be awesome.

### CODE REVIEW

**Comment by davestephens** [comment]
This is awesome, definitely needed, thank you! :+1: 

I reckon we can make it a little cleaner such that the container won't need a manual restart or deletion when you switch from staging to production though:

* Change `traefik.toml` to `traefik.toml.j2` and update the template step
* Add a conditional block around the staging parameter in the `traefik.toml.j2`, something like:
   ```
   {% if traefik_production == false %}
     caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
   {% endif %}
   ```
* Add a conditional restart to the traefik docker container when the template step is changed (see how docker is restarted after the config changes for an example)

Also, is it worth documenting the difference between staging and production LetsEncrypt certs?

**Comment by C-J1** [comment]
Have a fresh look at the doco. I also force pushed and squashed some commits to make the branch a bit cleaner.

**Comment by C-J1** [comment]
@davestephens ping! :)

**Comment by davestephens** [comment]
I vaguely recall a conversation we had about removing the received cert between switching from staging -> production - did anything get done with that - or am I imagining it?

**Comment by C-J1** [comment]
Yeah we did have that convo. I've been focusing on Real Life (tm) lately :D

I'll get to it as soon as I can.

Regards,

CJ

**Comment by davestephens** [comment]
That's fine, I just couldn't find where we had the conversation so was
checking I'd not imagined it! I might sort it this week if I get a chance,
assuming that's ok with you?

**Comment by C-J1** [comment]
Of course

**Comment by davestephens** [comment]
Now supported in Traefik Ansible role 👍

**Pull request closed without merging**
