### PR TITLE
Add support for watchtower

### PR DESCRIPTION
**Pull request by C-J1**
Sorry about the excessive merge commits in here. I did them before I knew better.

### CODE REVIEW

**Comment by davestephens** [comment]
Have a read of this - you can squash your commits into one sane one ;-)

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by davestephens** [comment]
So this is an interesting one. I'm currently working on a feature to pin containers to a specific image version so that upgrades are a bit more controlled. Bear in mind that a new image version can often equal a completely new software version with breaking changes - not cool for stability or someone that wants it to "just work" because they're fed up of FreeNAS (ie, me). After running ansible-nas for a year or so multiple containers were updated and subsequently busted by these types of upgrades - transmission-with-openvpn, grafana and Portainer come to mind. 

That said, I get that there are people that want the latest and greatest as soon as they are available so I *am* happy to include Watchtower - I just don't think it should be enabled by default.

**Comment by C-J1** [comment]
Sure, I can see the the desire for stability over all. Definitely an important feature on the "just work" front.

That said, there are options to manage which containers get auto updated  or not:

`--label-enable Watch containers where the com.centurylinklabs.watchtower.enable label is set to true.`

And no problems about not having it enabled by default. I'll switch that around and try to squash. I might have to delete my remote repo to do it, so not sure what will happen to this PR :D

**Comment by C-J1** [comment]
Closing this due to new, improved, clean history PR #24

**Pull request closed without merging**
