### PR TITLE
ENHANCMENT: Traefik - add ability to use rules.toml file

### PR DESCRIPTION
**Pull request by bcurran3**
**What this PR does / why we need it**:

Adds ability to use a rules.toml file to redirect to websites outside of Ansilbe-NAS

**Which issue (if any) this PR fixes**:

Fixes #

**Any other useful info**:

### CODE REVIEW

**Comment by davestephens** [comment]
This doesn't provide any way to customise the file referenced in the config. Is this PR complete?

**Review by davestephens — CHANGES_REQUESTED** [review]
This doesn't provide any way to customise the file referenced in the config. Is this PR complete?

**Comment by bcurran3** [comment]
Subjective. I would say yes. I considered a template but the possibilities to be in that template are endless; it's too open. Plus if you edit roles.toml directly in a template setup, it'll be overwritten. With that said  a list variable to insert into the template might work.

**Comment by davestephens** [comment]
The config reference will load the file from within the container. What puts it there?

**Comment by davestephens** [comment]
Closing as not something I want to support

**Pull request closed without merging**
