### PR TITLE
Make subdomains editable

### PR DESCRIPTION
**Pull request by animeai**
I've needed to tweak subdomains to make them a little more memorable and I don't think we should be editing the /tasks/*.yml files as these get overwritten.

### CODE REVIEW

**Comment by davestephens** [comment]
In theory I like this change, but I think it needs some documentation per the discussion in #109.

People need to be aware that changing subdomains and restarting traffic counts towards the LetsEncrypt rate limit. I *believe* that changing the cert SANS (subdomains) will count towards the "duplicate certs per week" limit imposed by LetsEncrypt, which is 5. e.g., you can play with the subdomains and re-request a certificate five times in one week before you get blocked and have to wait.

There is a way around this which would be to use the staging LetsEncrypt environment, but #35 was never completed which then adds a manual step in between switching between staging/prod.

**Comment by animeai** [comment]
@davestephens Sounds good to me, I'll word something up after the #193 merge. It'll be a headache if I go changing install instructions now!

**Comment by animeai** [comment]
Looking at the rate limits https://letsencrypt.org/docs/rate-limits/ - "Certificates registered per domain" is capped at 50 per week. The Duplicate Certificate rate is 5 per week though - I think we're more likely to be hitting this one.

We will also have to be careful in the future if we hit over 100 subdomains as 100 is the maximum names per certificate.

**Comment by bcurran3** [comment]
> I think we're more likely to be hitting this one.
> 
> We will also have to be careful in the future if we hit over 100 subdomains as 100 is the maximum names per certificate.

I think this is all VERY conditional depending on a user's configuration; very much a documentation warning... not so much a we-need-to-be-careful-with-the-setup-scripts-situation. Ansible-NAS could have the possibility to setup 20,000 sub-domains but if a user's configuration only consists of 20... not a concern.

Something along the lines of:

WARNING: When using LetsEncrypt blahblahblah, use of more then X sub-domains may cause blahblahbalh. Please refer to https://linkblahblbahblah

image

**Comment by davestephens** [comment]
@bcurran3 If you look at the Traefik config you'll see that we request a cert for *all* subdomains whether they are enabled or not, so @animeai's concerns are valid. 

We do this so the certificate is only re-requested when new applications are added, but it does come with the downside of requesting a lot of SANs per cert - which as stated above, has a limit of 100.

**Comment by bcurran3** [comment]
Thanks. Good to know. One of these days I need to checkout Traefik but don't think I personally have a need since I use a VPN to home all the time.

**Comment by davestephens** [comment]
Closing as now supported via wildcard certs and shift to ansible roles 👍

**Pull request closed without merging**
