### PR TITLE
nas.yml additions for Gotify

### PR DESCRIPTION
**Pull request by bcurran3**

### CODE REVIEW

**Comment by bcurran3** [comment]
This can't pass until the other additions are merged.

**Comment by animeai** [comment]
I would suggest a single pull request for a single feature. There is no need whatsoever to make a PR for every file edited... It makes it a lot harder to see whether the code changes or additions will actually work if they are all separated. If you were worried about my #178 being rejected, that's because I made several feature changes in a single PR that changed a massive chunk of the code base.

**Comment by bcurran3** [comment]
See comments in https://github.com/davestephens/ansible-nas/pull/195

**Comment by animeai** [comment]
@bcurran3 Apologies! :) I hadn't realised dave had already mentioned this to you... Your best bet is to close these multiple PR and reopen them as a single PR. If you need a hand or help I can do so via discord - let me know here and I'll give you my username.

**Comment by davestephens** [comment]
@bcurran3 @animeai You could also join the Ansible-NAS Gitter, quite a few people hang out in there. https://gitter.im/Ansible-NAS/Chat

**Comment by bcurran3** [comment]
@animeai - no worries. I might take you up on that. I only use GH as a place to backup and publicly display files. Would appreciate a few basics on how to actually use it for collaboration. 

@davestephens - I'll check it out again. When I first discovered AN, I explored the Gitter channel and found it.... "unresponsive" (Does that sound better than "dead?"). I know this is all new and building momentum so I'll have to go investigate again.

**Comment by bcurran3** [comment]
@animeai or @davestephens or @ANYONE!

Is it possible to clone ansible-nas locally (yes), edit the files (yes), and then somehow push a PR via CLI? 

That way I could make multiple clones for each PR and keep them out of each other's way.

**Comment by davestephens** [comment]
Yes, you use git to create a branch, then you have one branch per pull request. This is what I was referring to when I mentioned learning git, branching and pull requests in https://github.com/davestephens/ansible-nas/pull/195#issuecomment-571303425.  

I'm going to close this as we're having the same conversation across multiple issues, and the chat is now completely unrelated to the original issue.

**Comment by animeai** [comment]
@bcuran3 if you use windows, try github desktop.

**Comment by davestephens** [comment]
...or use git on the shell. Google how to create branches.

Will be something like `git checkout -b feature/new-thing`.

GUIs - GitHub desktop as above, sourcetree, gitk (comes with git),
gitkraken...loads more if you look.

**Pull request closed without merging**
